### ISSUE TITLE
env: HumanoidStandup-v1 error

### ISSUE THREAD

**Issue by zdx3578** [joschu/modular_rl#2]
Using Theano backend.
[2016-05-28 11:20:04,559] Making new env: HumanoidStandup-v1
policy gradient config {'lam': 0.97, 'cg_damping': 0.1, 'env': 'HumanoidStandup-v1', 'plot': False, 'activation': 'tanh', 'agent': 'modular_rl.agentzoo.TrpoAgent', 'outfile': '/tmp/a.h5', 'max_kl': 0.01, 'timestep_limit': 1000, 'video': 1, 'snapshot_every': 0, 'parallel': 0, 'n_iter': 1500, 'load_snapshot': '', 'filter': 1, 'use_hdf': 0, 'seed': 0, 'hid_sizes': [64, 64], 'timesteps_per_batch': 25000, 'gamma': 0.995, 'metadata': ''}
Traceback (most recent call last):
  File "run_pg.py", line 61, in <module>
    run_policy_gradient_algorithm(env, agent, callback=callback, usercfg = cfg)
  File "/Users/lmj/develop/gym-modular_rl/modular_rl/core.py", line 88, in run_policy_gradient_algorithm
    paths = get_paths(env, agent, cfg, seed_iter)
  File "/Users/lmj/develop/gym-modular_rl/modular_rl/core.py", line 106, in get_paths
    paths = do_rollouts_serial(env, agent, cfg["timestep_limit"], cfg["timesteps_per_batch"], seed_iter)
  File "/Users/lmj/develop/gym-modular_rl/modular_rl/core.py", line 143, in do_rollouts_serial
    path = rollout(env, agent, timestep_limit)
  File "/Users/lmj/develop/gym-modular_rl/modular_rl/core.py", line 127, in rollout
    rew = agent.rewfilt(rew)
  File "/Users/lmj/develop/gym-modular_rl/modular_rl/agentzoo.py", line 103, in rewfilt
    return self.rewfilter(rew)
  File "/Users/lmj/develop/gym-modular_rl/modular_rl/filters.py", line 31, in **call**
    if update: self.rs.push(x)
  File "/Users/lmj/develop/gym-modular_rl/modular_rl/running_stat.py", line 11, in push
    assert x.shape == self._M.shape
AssertionError

**Comment by zdx3578** [comment]
get result
in HumanoidStandup-v1: env out rew: [ 1.44062397]
because   reward = uph_cost - quad_ctrl_cost - quad_impact_cost
in humanoid : reward = lin_vel_cost - quad_ctrl_cost - quad_impact_cost + alive_bonus ; alive_bonus=5
so  env out rew: 5.35410772259

will fix in HumanoidStandup.py

**Comment by zdx3578** [comment]
i find the cause; need some time fix in HumanoidStandup-v1 model;

fixed!

**Comment by joschu** [comment]
OK, so the problem is in the Environment?

**Comment by zdx3578** [comment]
yes error is because env ,this issue can be close.
