### ISSUE TITLE
Error using set_value and get_value in agentzoo.py

### ISSUE THREAD

**Issue by hashhar** [joschu/modular_rl#20]
Pip log:

```
funcsigs (1.0.2)
gym (0.8.1)
h5py (2.7.0)
Keras (2.0.4)
keras-rl (0.3.0)
mock (2.0.0)
numpy (1.12.1)
pbr (3.0.0)
pip (9.0.1)
protobuf (3.3.0)
pyglet (1.2.4)
PyYAML (3.12)
requests (2.13.0)
scipy (0.19.0)
setuptools (27.2.0)
six (1.10.0)
tabulate (0.7.7)
tensorflow (1.1.0)
Theano (0.9.0)
Werkzeug (0.12.1)
wheel (0.29.0)
```

Traceback:
```
Using TensorFlow backend.
[2017-05-05 15:59:47,006] Making new env: CartPole-v0
Traceback (most recent call last):
  File "./run_pg.py", line 34, in <module>
    agent = agent_ctor(env.observation_space, env.action_space, cfg)
  File "/media/Resources/major-project/modular_rl/modular_rl/agentzoo.py", line 118, in __init__
    policy, self.baseline = make_mlps(ob_space, ac_space, cfg)
  File "/media/Resources/major-project/modular_rl/modular_rl/agentzoo.py", line 42, in make_mlps
    Wlast.set_value(Wlast.get_value(borrow=True)*0.1)
AttributeError: 'Variable' object has no attribute 'set_value'
[2017-05-05 15:59:47,041] Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/a.h5.dir')
```

I am trying to run the examples. I installed the latest tensorflow and keras packages and the above error came.

I also tried using the old versions (keras=1.0.1) and (tensorflow=0.7.1) but still couldn't get it to work.

Changing `Wlast = net.layers[-1].W` to `Wlast = net.layers[-1].kernel` fixes the first issue but there are lot of other issues too.

**Comment by abhinavrai44** [comment]
@hashhar You are using Tensorflow in the backend. Switch to theano to resolve the error.

**Comment by LiberiFatali** [comment]
@hashhar @abhinavrai44  What should I do to use Tensorflow backend for this repo, instead of Theano?

**Comment by AnujaNagare** [comment]
@LiberiFatali  
$HOME/.keras/keras.json
Edit "backend": from “theano” to “tensorflow”
