### ISSUE TITLE
Problem in net.add(ConcatFixedStd())

### ISSUE THREAD

**Issue by larakim** [joschu/modular_rl#27]
Hi there,
I am trying to use your code to train some new pybullet environment. Here is my Pip log:
Keras (2.0.2)
Markdown (2.6.11)
mock (2.0.0)
numpy (1.13.3)
pbr (3.1.1)
Pillow (5.0.0)
pip (9.0.1)
protobuf (3.5.1)
pybullet (1.7.4)
pyglet (1.2.4)
Pyste (0.9.10)
PyYAML (3.12)
requests (2.18.4)
roboschool (1.0, /home/laraki/roboschool)
scikit-learn (0.19.1)
scipy (1.0.0)
setuptools (20.7.0)
six (1.11.0)
sklearn (0.0)
statistics (1.0.3.5)
tabulate (0.8.2)
tensorflow (1.4.1)
tensorflow-tensorboard (0.4.0rc3)
tflearn (0.3.2)
Theano (0.9.0)
unity-lens-photos (1.0)
urllib3 (1.22)
Werkzeug (0.14.1)
wheel (0.29.0)

Traceback:
sudo KERAS_BACKEND=theano python run_pg.py --gamma=0.995 --lam=0.97 --agent=modular_rl.agentzoo.TrpoAgent --max_kl=0.01 --cg_damping=0.1 --activation=tanh --n_iter=250 --seed=0 --timesteps_per_batch=5000 --env=InvertedPendulumBulletEnv-v0 --outfile=$outdir/InvertedPendulum-v0.h
pybullet build time: Dec  6 2017 15:03:38
Using Theano backend.
Traceback (most recent call last):
  File "run_pg.py", line 36, in <module>
    agent = agent_ctor(env.observation_space, env.action_space, cfg)
  File "/home/laraki/roboschool/agent_zoo/modular_rl/modular_rl/agentzoo.py", line 118, in __init__
    policy, self.baseline = make_mlps(ob_space, ac_space, cfg)
  File "/home/laraki/roboschool/agent_zoo/modular_rl/modular_rl/agentzoo.py", line 38, in make_mlps
    net.add(ConcatFixedStd())
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 455, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
TypeError: call() takes exactly 3 arguments (2 given)

I did fix all the issues related to net.layers but I don't know how to fix this one, any ideas?
Thanks in advance

**Comment by SiyuanLee** [comment]
I also meet this problem.

**Comment by d3473r** [comment]
I fixed the error in this fork: https://github.com/D3473R/modular_rl
